eureka:
  client:
    serviceUrl:
      enabled: true
      defaultZone: http://localhost:1111/eureka/   #注册中心地址
server:
  port: 1113    #当前zuul服务端口
spring:
  application:
    name: zuul #服务名
zuul:
  routes:  #配置路由
    api-a:
      path: /api-a/**
      serviceId: consumer1   #api-a 开头的请求跳转到  consumer1服务
#    api-b:
#      path: /api-b/**
#      serviceId: consumer2   #api-b 开头的请求跳转到 consumer2服务