eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/ #注册中心服务地址
server:
  port: 2222
spring:
  application:
    name: producer
  zipkin:
      base-url: http://localhost:8888